#!/usr/bin/env python

# Copyright (C) 2012 Israel Herraiz Tabernero

# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is furnished to do
# so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Authors : Israel Herraiz <israel.herraiz@upm.es>


"""
Point of entry to the main module of the program.
@author:       Israel Herraiz
@organization: Universidad Politecnica de Madrid
@copyright:    Universidad Politecnica de Madrid
@license:      
@contact:      israel.herraiz@upm.es
"""

import pymeasurer
import sys

if __name__ == "__main__":
    try:
        pymeasurer.start(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
    except KeyboardInterrupt:
        print >>sys.stderr, "\n\nReceived Ctrl-C or other break signal. Exiting."

